### ISSUE TITLE
Head overlay render issue

### ISSUE THREAD

**Issue by Hacksore** [bs-community/skinview3d#22] opened 2018-05-18 12:58 UTC
The hat overlay area seems have rendering issues when viewed in certain angles. As you can see when my headphones render the underside of the headphone is see through. Some type of blending or culling issue possibly?

![image](https://user-images.githubusercontent.com/996134/40235696-a5bb556c-5a70-11e8-9b9b-31fbed0297e4.png)

**Comment by yushijinhun** [comment] 2018-06-06 14:03
I cannot reproduce it. But if the surface where headphones are on is approximately perpendicular to the visual plane, there might be some accuracy problems.

**Comment by yushijinhun** [comment] 2018-06-06 17:50
I think this might have been fixed in 49011214969d958e8dd60221c260a82bd9110c2e. Could you test it?

**Comment by yushijinhun** [comment] 2018-07-05 14:31
On f91db772b5a0489323d7fc53347ad4adb7a9aa3e:
![default](https://user-images.githubusercontent.com/8373027/42329209-bc9bbcd8-80a2-11e8-8c10-11d8c1e58e86.png)

On 3b23444fa1112fbef6e76f4a5e8506e790422e93:
![default](https://user-images.githubusercontent.com/8373027/42329365-18785674-80a3-11e8-8fed-82a4c7925e61.png)

So it's fixed in #18.

**Closed by yushijinhun** 2018-07-05 14:31 UTC
Labels: bug
